name: ci

on:
  push:
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"
  PYTHON_VERSIONS: ""

jobs:

  test-filenames:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test file names
      run: bash tests/test_filenames.sh

  test-licenses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "dev@pawamoy.fr"
        git config --global user.name "Timothée Mazzucotelli"
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install Copier
      run: pip install copier copier-templates-extensions
    - name: Test licenses
      run: bash tests/test_licenses.sh

  test-project:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.python-version == '3.13'}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "dev@pawamoy.fr"
        git config --global user.name "Timothée Mazzucotelli"
  
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install Copier and uv
      run: pip install copier copier-templates-extensions uv

    - name: Test project generation and workflow
      run: bash tests/test_generate.sh
